// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABjfaGMhfLW0cvIk1fFPqk-ibDpxV_2-U',
    appId: '1:364990375311:web:ba4f441c76661ef6d097fa',
    messagingSenderId: '364990375311',
    projectId: 'coura-3ab8e',
    authDomain: 'coura-3ab8e.firebaseapp.com',
    storageBucket: 'coura-3ab8e.firebasestorage.app',
    measurementId: 'G-EJ29CLY018',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDPUt0Y1XPi8HeYvTlbIhjLDA1O-GIb1E',
    appId: '1:364990375311:android:0d1c2d8031be64d8d097fa',
    messagingSenderId: '364990375311',
    projectId: 'coura-3ab8e',
    storageBucket: 'coura-3ab8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3O4iRYkEgvr_zKlhTmr0vddETuTzcQQ',
    appId: '1:364990375311:ios:41bf026886a706bcd097fa',
    messagingSenderId: '364990375311',
    projectId: 'coura-3ab8e',
    storageBucket: 'coura-3ab8e.firebasestorage.app',
    iosClientId: '364990375311-a9o2g502i05m9e1kapvk42lmpuql683e.apps.googleusercontent.com',
    iosBundleId: 'com.example.couraApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl3O4iRYkEgvr_zKlhTmr0vddETuTzcQQ',
    appId: '1:364990375311:ios:41bf026886a706bcd097fa',
    messagingSenderId: '364990375311',
    projectId: 'coura-3ab8e',
    storageBucket: 'coura-3ab8e.firebasestorage.app',
    iosClientId: '364990375311-a9o2g502i05m9e1kapvk42lmpuql683e.apps.googleusercontent.com',
    iosBundleId: 'com.example.couraApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABjfaGMhfLW0cvIk1fFPqk-ibDpxV_2-U',
    appId: '1:364990375311:web:f1c99ddf35b2ad0bd097fa',
    messagingSenderId: '364990375311',
    projectId: 'coura-3ab8e',
    authDomain: 'coura-3ab8e.firebaseapp.com',
    storageBucket: 'coura-3ab8e.firebasestorage.app',
    measurementId: 'G-4EKJ8D6H2J',
  );
}
